INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'wiliamhw', 'Get AWS Certified', CURRENT_DATE, false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'wiliamhw', 'Get Azure Certified', CURRENT_DATE, false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'wiliamhw', 'Get GCP Certified', CURRENT_DATE, false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'wiliamhw', 'Learn DevOps', CURRENT_DATE, false);